# インストール可能なrubyバージョン一覧
# mise ls-remote ruby
#
# 不要なバージョン等を削除
# mise prune
#
# 利用できるプラグイン一覧
# mise plugins update
# mise plugins ls-remote
#
[tools]
# mise ls-remote --all
# mise ls-remote go
go = ['1.26.3']
"go:golang.org/x/tools/gopls" = "latest"
ruby = ['3.4.9', '4.0.5']
nodejs = ['24.13.1']
"npm:@google/gemini-cli" = "latest"
java = ['temurin-21.0.10+7.0.LTS', 'temurin-25.0.2+10.0.LTS']
opentofu = ['1.11.4']
terraform = "1.14.8"
python = ['3.14.3']

# awscli: 別のCPU typeがインストールされるので、brewで管理
# awscli = ['2.21.2', '2.21.3']
# mise outdated で確認
#
# mise upで、最新のやつインストールしなおし
aws-vault = 'latest'
tmux = '3.6b'
jq = 'latest'
alp = 'latest'
ripgrep = 'latest'
delta = 'latest'
lazygit = 'latest'
lsd = 'latest'
eza = 'latest'
yq = 'latest'
gh = 'latest'
direnv = 'latest'
typst = 'latest'
grpcurl = 'latest'
protoc = 'latest'
eksctl = '0.220.0'
kubectl = '1.34.3'
cloudflared = '2026.3.0'
golangci-lint = 'latest'

# profilecli: PyroscopeにpprofプロファイルのやりとりをするためのCLIツール
[tools."http:profilecli"]
version = "2.0.1"
platforms.macos-arm64.url = "https://github.com/grafana/pyroscope/releases/download/v{{version}}/profilecli_{{version}}_darwin_arm64.tar.gz"
platforms.macos-arm64.checksum = "sha256:2cee2f7a6b695ac6545ed4b284505290485778c43cf720ad468e42e10e2ce2c9"

# cage: ClaudeCodeをぶん回すために必要
#"go:github.com/Warashi/cage" = "latest"
[tools."http:cage"]
version = "0.1.13"
platforms.macos-arm64.url = "https://github.com/Warashi/cage/releases/download/v{{version}}/cage_Darwin_arm64.tar.gz"
platforms.macos-arm64.checksum = "sha256:29ccee40b34bb4013700e03b21882914f2625e81749dcd0dc3deec408cbac477"

[settings]
# idiomatic version fileを有効化するかどうか
# asdfやmiseなどのバージョン管理ツールに依存しない「言語毎に標準的なバージョンファイル」
# 例: .go-version
idiomatic_version_file_enable_tools = ["go"]


[env]
# geminiを起動すると、以下のような警告が出るため抑制する
# (node:89335) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
# (Use `node --trace-deprecation ...` to show where the warning was created)
# (node:89348) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
NODE_OPTIONS = "--disable-warning=DEP0040"
